plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
}

configurations {
    markista
}

dependencies {
    markista("io.github.sandydunlop:markista:0.2.1")
}

allprojects {
    apply plugin: 'java'
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

java {
    withJavadocJar()
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}


subprojects {
    apply plugin: 'java'

    javadoc {
        title = 'My Project API'
        version = '1.0'
        destinationDir = file("${rootProject.buildDir}/docs/${project.name}")
        options {
            encoding = 'UTF-8'
            links 'https://docs.oracle.com/en/java/javase/24/docs/api'

            doclet = 'io.github.sandydunlop.markista.doclet.MarkdownDoclet'
            docletpath = rootProject.configurations.markista
            addStringOption("-project-path", "${project.rootDir}")
            addBooleanOption("-flatten-packages", true)
            addBooleanOption("-flatten-modules", true)
        }
        options.showFromPrivate()
        options.verbose()
    }
}

